### ISSUE TITLE
Create AMI-UK survey

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/AMI-images#2]
Consider need for an occurrence attribute for image classification score

**Comment by johnvanbreda** [comment]
Do you have a specification for this attribute @DavidRoy? E.g. an integer value from 0 - 100?

Are there any other attributes captured by the AMI system?

**Comment by DavidRoy** [comment]
@albags can you confirm that this attribute is a value between 0 and 1?
@johnvanbreda please setup that way for now

**Comment by johnvanbreda** [comment]
Attribute added - will await confirmation before closing.

**Comment by albags** [comment]
yes, the attribute will be an integer. I would say normally 1.

**Comment by DavidRoy** [comment]
Is that right?  Isn't it a floating point number, i.e. between 0 and 1?  so can be 0.80 classification score for example?

**Comment by albags** [comment]
Sorry I got consufed when you say occurrences I thought you meant the occurrence attribute/field in Indicia. Yes, the score coming from the classifier will be an integer between 0 and 1 always.

**Comment by johnvanbreda** [comment]
Thanks - I've implemented the attribute as a float between 0 and 1 so closing.
