### ISSUE TITLE
Create AMI drupal site

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/AMI-images#3]
- [x] submit website request form under AMBER
- [x] decide on url (e.g. ukceh-ami.info)
- [x] setup required Indicia modules
- [x] add required pages (import, explore, download, verify-photo)
- [x] add role = verifier
- [x] add ability to assign users to role

**Comment by DavidRoy** [comment]
ukceh subdomain
ami.ceh.ac.uk

**Comment by johnvanbreda** [comment]
Are the following required?
* Privacy notice
* Terms and conditions
* About page
* Contact

We have the following options for user registration:
* Users can self-register
* Users can self-register but admin must approve account
* Users can only be registered by an admin

Which option is required? The first 2 would need addition of anti-spam modules.

**Comment by DavidRoy** [comment]
Yes to additional pages, although no urgency for these to be populated.
Can you create blank pages for this.

User registration: users can only be registered by an admin

**Comment by johnvanbreda** [comment]
One more question - is there any need for users to accept terms and conditions (or privacy notice)?

**Comment by DavidRoy** [comment]
No. This site is for use by UKCEH project staff, and may be extended to other organisations.  But is not public facing.

**Comment by johnvanbreda** [comment]
Done - see https://dev-ceh-ami.pantheonsite.io/
