### ISSUE TITLE
Establish process for importing images

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/AMI-images#5]
- [ ] import occurrences using standard importer
- [ ] process for importing a batch of images to a server location

**Comment by johnvanbreda** [comment]
At the moment the Media Path 1,2,3 and 4 destination attributes allow import of up to 4 photos per record. Will test that the photos display correctly from a remote location once some data are in the system.

**Comment by DavidRoy** [comment]
images to be stored elsewhere.  Drupal initially

**Comment by DavidRoy** [comment]
@BirenRathod can you setup the Drupal site to enable a batch of images to be uploaded with a url to access each individual image

**Comment by BirenRathod** [comment]
@DavidRoy you can upload images using this URL->https://dev-ceh-ami.pantheonsite.io/media/bulk-upload/species_images_bulk_upload 
The maximum you can upload is up to 100MB in one go. 

After uploading those images, those images will appear here-> https://dev-ceh-ami.pantheonsite.io/admin/content/media. 
At present, This is an initial setup I have done.

**Comment by DavidRoy** [comment]
Thanks. That works with a single test - I can upload an image and it is accessible via a url, e.g. 
https://dev-ceh-ami.pantheonsite.io/sites/default/files/2023-06/p17b44i36q4emop31l5jonglecv.jpg

We now need to work out a way to include the image file name in the database so we can link to specific images when importing occurrences

@BirenRathod can you suggest a way to do that?  Is the original file-name stored in Drupal somewhere?

**Comment by DavidRoy** [comment]
@BirenRathod ignore my question as I see the url does include the file name! I think this gives us what we need, thanks!

**Comment by BirenRathod** [comment]
@DavidRoy Yes, that file name is stored everywhere like in the database and in the image folder too.

**Comment by johnvanbreda** [comment]
@DavidRoy a possible task here then is to update the Indicia code to support Drupal media as a source for the images. At the moment, if an image is uploaded to the warehouse we can generate a thumbnail and medium size version of the file by adding thumb- or med- before the filename. The verification tool would currently have to load the full version of the file even if resized in the browser to a small thumbnail as the code doesn't understand Drupal's media system, so adding support for this would make image reviewing more efficient. This may not be needed if the Drupal media upload is only a temporary solution though.

**Comment by DavidRoy** [comment]
@johnvanbreda good point. I think the AMI images are reasonably low resolutions (as cropped to individual insects from a larger image) so may be ok.  I'll raise a new issue for the Indicia code support if needed
