### ISSUE TITLE
Enable multi-photo select and verify

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/AMI-images#7]
Same requirement as:
https://github.com/BiologicalRecordsCentre/iRecord/issues/1483

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
@johnvanbreda thanks!  Has this also been implemented on the iRecord version of the photo-led verification page?

**Comment by johnvanbreda** [comment]
No, it's in the queue of stuff that will be applied next time I do a full update of the code. I can prioritise this if you want me to.

**Comment by DavidRoy** [comment]
No need to prioritise, just checking it didn't get overlooked
